# Generated by Django 3.1.1 on 2020-09-22 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_imageurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='release_date',
            new_name='year',
        ),
    ]
