# Generated by Django 3.1.1 on 2020-09-22 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20200921_2056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='imageURL',
            new_name='image',
        ),
    ]
